### ISSUE TITLE
A user can search for a task by specifying any of the keywords

### ISSUE THREAD

**Issue by petercd** [cs2103jan2015-t16-3c/Main#6]
so that searching becomes flexible and fast.

**Comment by nictheburden** [comment]
void application::search(string &input)
{
    const int SEARCH_INDEX = 7;
    string token;
    token = input.substr(SEARCH_INDEX);
    for (int i = 0; i < (int)_content.size(); i++)
    {
        if (_content[i].find(token) != string::npos) {
            cout << _content[i] << endl;
        }
    }
    cout << token << " not found" << endl;
}
